server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.101:3306/content_center?characterEncoding=utf-8
    username: yuyongtao
    password: yuyongtao



  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 192.168.71.100:8848
        cluster-name: BJ
        # namespace: 56116141-d837-4d15-8842-94e153bb6cfb
    sentinel:
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-centerClassName: com.netflix.loadbalancer.RandomRule